# coding: utf-8

"""
    Priceless Planet Data Services API

    A platform to calculate user's sustainability metrics  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.impact_metric import ImpactMetric  # noqa: E501
from openapi_client.rest import ApiException

class TestImpactMetric(unittest.TestCase):
    """ImpactMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImpactMetric
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.impact_metric.ImpactMetric()  # noqa: E501
        if include_optional :
            return ImpactMetric(
                trees = 2.32, 
                carbon_sequestered = 1234.45, 
                conversion_rate = 2.3456, 
                conversion_rate_date = 'Sun Mar 14 20:00:00 EDT 2021'
            )
        else :
            return ImpactMetric(
        )

    def testImpactMetric(self):
        """Test ImpactMetric"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
