# coding: utf-8

"""
    Priceless Planet Data Services API

    A platform to calculate user's sustainability metrics  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.planting_projects_api import PlantingProjectsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPlantingProjectsApi(unittest.TestCase):
    """PlantingProjectsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.planting_projects_api.PlantingProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_planting_project(self):
        """Test case for get_planting_project

        Retrieve a planting project  # noqa: E501
        """
        pass

    def test_get_planting_projects(self):
        """Test case for get_planting_projects

        Retrieve planting projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
