# coding: utf-8

"""
    Priceless Planet Data Services API

    A platform to calculate user's sustainability metrics  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.impact_metrics_api import ImpactMetricsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestImpactMetricsApi(unittest.TestCase):
    """ImpactMetricsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.impact_metrics_api.ImpactMetricsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_impact_metrics(self):
        """Test case for get_impact_metrics

        Impact Metrics Calculation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
