# coding: utf-8

"""
    Priceless Planet Data Services API

    A platform to calculate user's sustainability metrics  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.planting_project import PlantingProject  # noqa: E501
from openapi_client.rest import ApiException

class TestPlantingProject(unittest.TestCase):
    """PlantingProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlantingProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.planting_project.PlantingProject()  # noqa: E501
        if include_optional :
            return PlantingProject(
                id = 1, 
                country_name = 'Brazil', 
                target = 2000000, 
                trees_planted = 1680000, 
                area_covered = 94, 
                carbon_sequestered = 50, 
                name = 'Amazon Rainforest', 
                description = 'The Atlantic Forest, also known as Mata Atlantica, once covered 130 million hectares across Brazil. Now, this tropical rainforest ecosystem is home to more than half of the country’s population.', 
                images = [
                    openapi_client.models.image.Image(
                        url = 'https:image', )
                    ]
            )
        else :
            return PlantingProject(
        )

    def testPlantingProject(self):
        """Test PlantingProject"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
