# coding: utf-8

"""
    Priceless Planet Data Services API

    A platform to calculate user's sustainability metrics  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: apisupport@mastercard.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class PlantingProjects(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'count': 'int',
        'limit': 'int',
        'offset': 'int',
        'total': 'int',
        'planting_projects': 'list[PlantingProject]'
    }

    attribute_map = {
        'count': 'count',
        'limit': 'limit',
        'offset': 'offset',
        'total': 'total',
        'planting_projects': 'plantingProjects'
    }

    def __init__(self, count=None, limit=None, offset=None, total=None, planting_projects=None, local_vars_configuration=None):  # noqa: E501
        """PlantingProjects - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._count = None
        self._limit = None
        self._offset = None
        self._total = None
        self._planting_projects = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset
        if total is not None:
            self.total = total
        if planting_projects is not None:
            self.planting_projects = planting_projects

    @property
    def count(self):
        """Gets the count of this PlantingProjects.  # noqa: E501

        The number of items that are in this offset batch  # noqa: E501

        :return: The count of this PlantingProjects.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this PlantingProjects.

        The number of items that are in this offset batch  # noqa: E501

        :param count: The count of this PlantingProjects.  # noqa: E501
        :type count: int
        """

        self._count = count

    @property
    def limit(self):
        """Gets the limit of this PlantingProjects.  # noqa: E501

        The number of items the list has been limited to  # noqa: E501

        :return: The limit of this PlantingProjects.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PlantingProjects.

        The number of items the list has been limited to  # noqa: E501

        :param limit: The limit of this PlantingProjects.  # noqa: E501
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this PlantingProjects.  # noqa: E501

        The number of items the start of the list has been offset from  # noqa: E501

        :return: The offset of this PlantingProjects.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PlantingProjects.

        The number of items the start of the list has been offset from  # noqa: E501

        :param offset: The offset of this PlantingProjects.  # noqa: E501
        :type offset: int
        """

        self._offset = offset

    @property
    def total(self):
        """Gets the total of this PlantingProjects.  # noqa: E501

        The total number of items that are in the entire collection  # noqa: E501

        :return: The total of this PlantingProjects.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this PlantingProjects.

        The total number of items that are in the entire collection  # noqa: E501

        :param total: The total of this PlantingProjects.  # noqa: E501
        :type total: int
        """

        self._total = total

    @property
    def planting_projects(self):
        """Gets the planting_projects of this PlantingProjects.  # noqa: E501

        List of planting projects  # noqa: E501

        :return: The planting_projects of this PlantingProjects.  # noqa: E501
        :rtype: list[PlantingProject]
        """
        return self._planting_projects

    @planting_projects.setter
    def planting_projects(self, planting_projects):
        """Sets the planting_projects of this PlantingProjects.

        List of planting projects  # noqa: E501

        :param planting_projects: The planting_projects of this PlantingProjects.  # noqa: E501
        :type planting_projects: list[PlantingProject]
        """

        self._planting_projects = planting_projects

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlantingProjects):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PlantingProjects):
            return True

        return self.to_dict() != other.to_dict()
